---
# - include_tasks:
#   - "../install/{{ ansible_pkg_mgr }}.yml"

- name: Add new user 'vector'
  become: true
  ansible.builtin.user:
    name: "vector"
    state: present
    shell: "/sbin/nologon"
- name: Download vector archive
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vector_arch }}-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-{{ vector_arch }}-unknown-linux-gnu.tar.gz"
    mode: '0644'
- name: Unzip vector archive
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/vector-{{ vector_version }}-{{ vector_arch }}-unknown-linux-gnu.tar.gz"
    dest: "/tmp/"
- name: Copy vector to /usr/bin/
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/vector-{{ vector_arch }}-unknown-linux-gnu/bin/vector"
    dest: "/usr/bin/"
    mode: '0755'
- name: Copy default config to /etc/default/
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/vector-{{ vector_arch }}-unknown-linux-gnu/etc/systemd/vector.default"
    dest: "/etc/default/vector"
    mode: '0644'
- name: Include yaml to default config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/vector
    line: "VECTOR_CONFIG_YAML=/etc/vector/config.yaml"
- name: Create etc directory
  become: true
  ansible.builtin.file:
    path: "/etc/vector"
    state: directory
    mode: "0755"
- name: Template file
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/vector-{{ vector_arch }}-unknown-linux-gnu/config/vector.yaml"
    dest: /etc/vector/config.yaml
    mode: '0644'
- name: Create var directory
  become: true
  ansible.builtin.file:
    path: "/var/lib/vector"
    state: directory
    mode: "0777"
- name: Copy service vector
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/vector-{{ vector_arch }}-unknown-linux-gnu/etc/systemd/vector.service"
    dest: "/lib/systemd/system/"
    mode: '0755'
  notify: Start vector service

